export const words = [
  { word: "binary", hint: "Base-2 number system" },
  { word: "loop", hint: "A structure for repeating code" },
  { word: "array", hint: "Stores multiple values in a single variable" },
  { word: "object", hint: "A data structure with key-value pairs" },
  { word: "debug", hint: "Process of fixing bugs" },
  { word: "syntax", hint: "Rules of a programming language" },
  { word: "script", hint: "A file containing program code" },
  { word: "stack", hint: "LIFO data structure" },
  { word: "queue", hint: "FIFO data structure" },
  { word: "react", hint: "A JavaScript library for building UIs" },
  { word: "hook", hint: "Special function in React" },
  { word: "node", hint: "JavaScript runtime environment" },
  { word: "event", hint: "An action like a click or keypress" },
  { word: "class", hint: "Template for creating objects" },
  { word: "method", hint: "Function defined in a class" },
  { word: "state", hint: "Stores dynamic data in components" },
  { word: "props", hint: "Data passed to components" },
  { word: "fetch", hint: "Used to request data from APIs" },
  { word: "async", hint: "Keyword for asynchronous functions" },
  { word: "await", hint: "Waits for async operation to complete" },
  { word: "closure", hint: "Function with preserved lexical scope" },
  { word: "promise", hint: "Represents eventual completion of async task" },
  { word: "module", hint: "Reusable piece of code" },
  { word: "export", hint: "Makes code available to other files" },
  { word: "import", hint: "Brings code from another module" },
  { word: "token", hint: "Piece of data used for authentication" },
  { word: "branch", hint: "Git command to work on a new feature" },
  { word: "merge", hint: "Combines code from branches" },
  { word: "commit", hint: "Saves changes in git" },
  { word: "deploy", hint: "Publish application to the web" },
  { word: "bug", hint: "An error in the program" },
  { word: "api", hint: "Interface between two software applications" },
  { word: "url", hint: "Web address" },
  { word: "json", hint: "Lightweight data format" },
  { word: "html", hint: "Standard language for creating webpages" },
  { word: "css", hint: "Styles HTML elements" },
  { word: "git", hint: "Version control system" },
  { word: "npm", hint: "JavaScript package manager" },
  { word: "dom", hint: "Represents HTML structure" },
  { word: "ide", hint: "Tool for writing and debugging code" },
  { word: "bash", hint: "Unix shell and command language" },
  { word: "axios", hint: "Promise-based HTTP client" },
  { word: "router", hint: "Defines app routes in React" },
  { word: "login", hint: "Action to access an account" },
  { word: "logout", hint: "Action to exit an account" },
  { word: "auth", hint: "Short for authentication" },
  { word: "token", hint: "Used for session validation" },
  { word: "crud", hint: "Create, Read, Update, Delete operations" },
  { word: "form", hint: "User input component" },
  { word: "data", hint: "Information processed or stored" },
  { word: "cache", hint: "Stores data for quick access" },
  { word: "loop", hint: "Used to repeat instructions" },
  { word: "map", hint: "Array method for transforming values" },
  { word: "filter", hint: "Returns array elements that match a condition" },
  {
    word: "reduce",
    hint: "Applies function to array elements to reduce them to a single value",
  },
  { word: "key", hint: "Unique identifier in a list" },
  { word: "value", hint: "Data stored in a key" },
  { word: "type", hint: "Specifies variable kind (e.g., string, number)" },
  { word: "null", hint: "Intentional absence of value" },
  { word: "undefined", hint: "Variable declared but not assigned" },
  { word: "boolean", hint: "True or false" },
  { word: "number", hint: "Numeric data type" },
  { word: "string", hint: "Text data type" },
  { word: "function", hint: "Block of reusable code" },
  { word: "variable", hint: "Stores value for later use" },
  { word: "const", hint: "Declares a constant variable" },
  { word: "let", hint: "Declares a block-scoped variable" },
  { word: "var", hint: "Old way to declare variables" },
  { word: "eval", hint: "Executes code from a string" },
  { word: "hoisting", hint: "JS behavior of moving declarations to the top" },
  { word: "scope", hint: "Defines where variables are accessible" },
  { word: "block", hint: "A section of code enclosed in braces" },
  { word: "compile", hint: "Convert code into machine-readable form" },
  { word: "build", hint: "Transform code for production" },
  { word: "refactor", hint: "Rewriting code to improve it" },
  { word: "testing", hint: "Checking if code works as expected" },
  { word: "unit", hint: "Type of test for isolated components" },
  { word: "lint", hint: "Tool for code style checking" },
  { word: "error", hint: "Something went wrong in code" },
  { word: "exception", hint: "Error that can be caught" },
  { word: "try", hint: "Used to catch exceptions" },
  { word: "catch", hint: "Handles the exception" },
  { word: "finally", hint: "Runs after try/catch" },
  { word: "throw", hint: "Used to raise an exception" },
  { word: "regex", hint: "Pattern used to match strings" },
  { word: "escape", hint: "Used to avoid special meaning" },
  { word: "char", hint: "Single character" },
  { word: "bit", hint: "Smallest data unit" },
  { word: "byte", hint: "Group of 8 bits" },
  { word: "local", hint: "Scope within function or block" },
  { word: "global", hint: "Accessible everywhere" },
  { word: "server", hint: "Provides resources or data to clients" },
  { word: "client", hint: "Requests data from server" },
  { word: "backend", hint: "Handles logic, database, server" },
  { word: "frontend", hint: "Handles UI and user interaction" },
  { word: "render", hint: "Displays UI" },
  { word: "component", hint: "Reusable UI element in React" },
  { word: "jsx", hint: "JS syntax extension for React" },
  { word: "spa", hint: "Single Page Application" },
  { word: "framework", hint: "Provides structure for development" },
  { word: "library", hint: "Collection of reusable functions" },
];
